# Generated by Django 3.0.5 on 2020-05-02 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zzs', '0002_auto_20200502_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='mvp_player',
            field=models.ForeignKey(default='ZZS - ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='zzs.MostValuablePlayer', verbose_name='MVP игрок'),
        ),
    ]
