# Generated by Django 3.0.5 on 2020-05-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzs', '0005_match_win_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='matches',
        ),
        migrations.AddField(
            model_name='team',
            name='matches',
            field=models.ManyToManyField(related_name='teams_games', to='zzs.Match', verbose_name='Матчи'),
        ),
    ]
