# Generated by Django 3.0.5 on 2020-05-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzs', '0008_auto_20200502_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
