# Generated by Django 3.0.5 on 2020-05-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzs', '0009_auto_20200502_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='teams',
            field=models.CharField(max_length=300, verbose_name='Команды'),
        ),
    ]
